// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package openadmin.model;


/**
 *  Control entity that represents the available actions in a form
 *	@version  1.1
 *  Created  18-03-2009
 *  LastModified  12-03-2022
 *  @author Alfred Oliver
 *  @author Vicent Borja
*/

import org.hibernate.validator.constraints.Length;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import openDao.model.Base;

@Entity
@Table(name = "action", schema = "control", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
@JsonIgnoreProperties(ignoreUnknown=true)
public class Action implements Base, java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -4370649534311822258L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Getter @Setter
	private Integer id;
	/**
	 *  Attribute that contains entitie's description, unique value
	 */
	@Length(max = 100)
	@NotNull
	@Getter @Setter
	private String description;
	
	@Getter @Setter
	private Byte groupid;
	
	@Length(max = 50)
	@Getter @Setter
	private String icon;
	/**
	 * 
	 */
	@ManyToOne
	@JoinColumn(name = "nameclass", nullable= false)
	@Getter @Setter
	private NameClass nameclass;
	
	/** Transient attribute that means that the system should make a log on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean debuglog = true;
	
	/** Transient attribute that means that the system should make a historic on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean historiclog = false;
	/**
	 * 
	 */
	
	
	/**
	 * Constructor of the class Action.
	 * without parameters
	 */
	public Action() {

	}
	
	

	
	

	
	
	
}
