// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package openadmin.model;

import jakarta.enterprise.inject.Default;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import openDao.annotation.Search;
import openDao.model.Base;

/**
 *  Control entity that links the role, menuitem and action entities
 *	@version  1.1
 *  Created  18-03-2009
 *  LastModified  13-03-2022
 *  @author Alfred Oliver
 *  @author Vicent Borja
*/

@Entity
@Table(name = "actionviewrole", schema = "control", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
@JsonIgnoreProperties(ignoreUnknown=true)
public class ActionViewRole implements Base, java.io.Serializable  {
	/**
	 * 
	 */
	private static final long serialVersionUID = -44021652449486335L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Getter @Setter
	private Integer id;
	/**
	 *  Attribute that contains entitie's description, unique value
	 */
	@Length(max = 30)
	@Default
	@Getter
	private String description;
	
	/** attribute that contain the relationship with role*/
	@ManyToOne
	@JoinColumn(name = "role", nullable= false)
	@Getter @Setter
	private Role role;
	
	
	/** attribute that contain the relationship with view*/
	@ManyToOne
	@JoinColumn(name = "menuitem", nullable= false)
	@Search(nameObjects= "Action:nameClass")
	@Getter @Setter
	private MenuItem menuItem;
	
	/** attribute that contain the relationship with view*/
	@ManyToOne
	@JoinColumn(name = "action", nullable= false)
	@Search(nameObjects= "MenuItem:nameClass")
	@Getter @Setter
	private Action action;
	
	
	/** Transient attribute that means that the system should make a log on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean debuglog = true;
	
	/** Transient attribute that means that the system should make a historic on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean historiclog = false;
	
	
	
	

	public void setDescription(String pDescription) {
		
		if(menuItem != null || action != null || role != null) {
			this.description = menuItem.getId() + "_" + role.getId() + "_" + action.getId() ;
	}else {
		this.description = pDescription;
		}
	
	}
}
