// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package openadmin.model;

import java.util.Date;

import org.hibernate.validator.constraints.Length;

import jakarta.annotation.ManagedBean;
import jakarta.enterprise.context.RequestScoped;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import openDao.annotation.NoSql;
import openDao.model.Base;

/**
 *  Control entity that defines the attributes of a form view
 *	@version  1.1
 *  Created  18-03-2009
 *  LastModified  12-03-2022
 *  @author Alfred Oliver
 *  @author Vicent Borja
*/


@Entity
@Table(name = "menuitem", schema = "control", uniqueConstraints = @UniqueConstraint(columnNames = "description") )
@JsonIgnoreProperties(ignoreUnknown=true)
public class MenuItem implements Base, java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 4749464261544273563L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Getter @Setter
	private Integer id;
	/**
	 * 
	 */
	/** attribute that contains the description, unique value*/
	@Length(max = 100)
	@NotNull
	@Getter
	private String description;
	
	/** attribute that contains the parent (recursion)*/
	@ManyToOne
	@JoinColumn(name="parent", nullable= true)
	@NoSql
	@Getter @Setter
	private MenuItem parent;
	
	@NotNull
	@Length(min = 1, max = 1)
	@Getter @Setter
	private String typenode = "c";
	
	@Length(max = 50)
	@Getter @Setter
	private String viewType;
	
	@Length(max = 250)
	@Getter @Setter
	private String viewCode;
	
	@Length(max = 50)
	@Getter @Setter
	private String icon;

	/**
	 * 
	 */
	
	/** Transient attribute that means that the system should make a log on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean debuglog = true;
	
	/** Transient attribute that means that the system should make a historic on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean historiclog = false;
	
	@Getter @Setter
	private Byte itemorder;

	public void setDescription(String pDescription) {
		
		
		this.description = pDescription.toLowerCase().replace(".", "_");
	}

	

}
