// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package openadmin.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import openDao.model.Base;


/**
 * <desc>Class with the name of the action routes</desc>
 * <responsibility>Creates relation between </responsibility>
 * <coperation>All classes dao</coperation>
 *	@version  0.1
 *	Create  18-03-2009
 * Modifier  16-01-2022
 * Author Alfred Oliver
*/

@Entity
@Table(name = "nameclass", schema = "control", uniqueConstraints = @UniqueConstraint(columnNames="description"))
@JsonIgnoreProperties(ignoreUnknown=true)
public class NameClass implements Base, java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8327810379078778132L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Getter @Setter
	private Integer id;
	/**
	 * 
	 */
	@NotNull
	@Length(min= 10, max = 80)
	@Getter @Setter
	private String description;	
	

	/** Transient attribute that means that the system should make a log on any JPA operation of this class*/
	@Transient 
	@Getter @Setter
	private boolean debuglog = true;
	
	/** Transient attribute that means that the system should make a historic on any JPA operation of this class*/
	@Transient
	@Getter @Setter
	private boolean historiclog = false;	
	
	
	
	/**
	 * Constructor of the class ActionClass.
	 * without parameters
	 */
	public NameClass() {
		
	}
	
	/**
	 * Constructor of the class ActionClass.
	 * @param pDescription, is the description, (unique value), of the ActionClass
	 */
	public NameClass(String pDescription) {
		
		this.description = pDescription;
	}
	
	


//	@Override
//	public void setId(Object pId) {
//		this.id = (int) pId;
//		
//	}



}
