// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package openadmin.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import openDao.model.Base;

/**
 *  Control entity that represents the aplications
 *	@version  1.1
 *  Created  18-03-2009
 *  LastModified  13-03-2022
 *  @author Alfred Oliver
 *  @author Vicent Borja
*/
@Entity
@Table(name = "program", schema = "control", uniqueConstraints = @UniqueConstraint(columnNames = "description"))
@JsonIgnoreProperties(ignoreUnknown=true)
public class Program implements Base, java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 5314118298809075989L;

	/**
	 * 
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	@Getter @Setter
	private Integer id;
	

	/** attribute that contains the program name (description), unique value*/
	@Length(min =3, max = 25)
	@NotNull
	@Getter @Setter
	private String description;
	
	@Length(max = 50)
	@Getter @Setter
	private String icon;
	
	/** Transient attribute that means that the system should make a log on any JPA operation of this class*/
	@Transient
	private boolean debuglog = true;
	
	/** attribute that contains the relationship with rol*/
	//@OneToMany(cascade = CascadeType.REFRESH, fetch = FetchType.EAGER, mappedBy = "program")
	//private Set<Role> role = new HashSet<Role>(0);

	/** Transient attribute that means that the system should make a historic on any JPA operation of this class*/
	@Transient
	private boolean historiclog = false;
	
	
	public Program() {
		
	}
	
	public Program(String pDescription) {
		
		this.description = pDescription.toLowerCase();
		
	}
	
	


	
}
